config/routes.rb
 # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  get "about-us", to: "about#index", as: :about

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"


  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  root to: "main#index"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :worker
end

app/models/user.rb
class User < ApplicationRecord
     
    has_secure_password
end

app/models/worker.rb
class Worker < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_worker

    def set_current_worker
        if session[:user_id]
        Current.worker = Worker.find_by(id: session[:user_id])
        end
    end

    def require_worker_logged_in!
        redirect_to sign_in_path, alert: "you must be signed in to do that." if Current.worker.nil?
        
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
           
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
        
    end
    def create
        @worker = Worker.find_by(email: params[:email])

        if @worker.present?
            PasswordMailer.with(worker: @worker).reset.deliver_now
        else
            redirect_to root_path, notice: "if an account with that email was found, we have sent a link to reset your password"
        end
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_worker_logged_in!
    
    def update
      if Current.worker.update(password_params)
        redirect_to root_path, notice: "Password Updated!"

      else
        render :edit
      end
    end

    def edit
      
    end

    private 

    def password_params
        params.require(:worker).permit(:password, :password_confirmation) 
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @worker = Worker.new
    end

    def create
        @worker = Worker.new(worker_params)
        if @worker.save!
        session[:user_id] = @worker.id
        redirect_to root_path, notice: "Successfully created account"
        else 
        flash[:alert] = "some thing was wrong"
        render :new
        end
      end
      
      private
      
      def worker_params
        params.require(:worker).permit(:email, :password, :password_confirmation)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    
    def create
        worker = Worker.find_by(email: params[:email])
        if worker.present? && worker.authenticate(params[:password])
        session[:user_id] = worker.id
        redirect_to root_path, notice: "Logged in successfully"
        else
            
        render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out" 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeZ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= render partial: "shared/navbar" %>
  <div class="container">
  
    <%= render partial: "shared/flash" %>
     <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex aling-items-center justify-content-center">
    <h1> Welcome To CodeZ</h1>
    </div>

app/views/password_resets/new.html.erb
<h1>Forgot your password</h1>

<%= form_with url: password_reset_path do |form| %>

    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "codez@gmail.com" %>
    </div>

    <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary"%> 
       </div>
    <% end %>

app/views/shared/_flash.html.erb
    <% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">      
      <%= flash[:notice] %>
    </div>
    <% end %>

    <% if flash[:alert] %>

    <div class="alert alert-warning mt-4" role="alert">
      <%= flash[:alert] %>
    </div>
    <% end %>


  

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link"%>
        
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.worker %>
          <li class="nav-item">
            <%= link_to Current.worker.email, edit_password_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
           <li class="nav-item">
           <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
           </li>
           <li class="nav-item">
           <%= link_to "Login", sign_in_path, class: "nav-link" %>
           </li>
           <% end %>
      </ul>
    </div>
  </div>
</nav>